main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main, name='main'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfoliosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

admin.site.site_header = 'DoniDev Portfolio Admin'

admin.site.site_title = 'DoniDev'

admin.site.index_title = "My personal portfolio site admin"

about/models.py
from django.db import models

from owner.models import Owner


class About(models.Model):
    starter = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    user = models.ForeignKey(Owner, on_delete=models.CASCADE)


    class Meta:
        verbose_name_plural ='about'

    def __str__(self):
        return f'About {self.user.full_name}'

contact/models.py
from django.db import models
from owner.models import Owner


class Contact(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    credentials = models.ForeignKey(Owner, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='contact/', null=True)


    class Meta:
        verbose_name_plural = 'contact'

    def __str__(self):
        return self.credentials.full_name

home/models.py
from django.db import models
from owner.models import Owner


class Skill(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Greeting(models.Model):
    starting = models.CharField(max_length=200)
    name = models.ForeignKey(Owner, on_delete=models.CASCADE,default='')
    intro = models.CharField(max_length=50, default='')
    skills = models.ManyToManyField(Skill)

    class Meta:
        verbose_name_plural = 'Introduction'

    def __str__(self):
        return f'{self.name.full_name} introduction'

main/models.py
from django.db import models

# Create your models here.

owner/models.py
from django.db import models

class Owner(models.Model):
    full_name = models.CharField(max_length=200)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=17)
    address = models.CharField(max_length=200)
    projects = models.IntegerField()
    images = models.ImageField(upload_to='images/')

    class Meta:
        verbose_name_plural = 'Owner'

    def __str__(self):
        return self.full_name

projects/models.py
from django.db import models

class ProjectIntro(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=400)

    def __str__(self):
        return self.title


class Project(models.Model):
    name = models.CharField(max_length=100)
    technology = models.CharField(max_length=200)
    image = models.ImageField(upload_to='projects/')
    link = models.URLField()

    def __str__(self):
        return self.name

resume/models.py
from django.db import models


class Field(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Activity(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    duration = models.CharField(max_length=120)
    job = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    location = models.CharField(max_length=200)


    def __str__(self):
        return self.field.name

    class Meta:
        verbose_name_plural = 'Activities'

services/models.py
from django.db import models


class Introduction(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Introduction'


class Service(models.Model):
    icon = models.CharField(max_length=50)
    name = models.CharField(max_length=120)
    heading = models.CharField(max_length=300)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from django.forms import Form


class ContactForm(Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)


    def clean_name(self):
        name = self.cleaned_data['name']
        alphabet = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz '
        for letter in name:
            if letter not in alphabet:
                raise forms.ValidationError('Name should be consists of letters only')

        return name

about/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, redirect
from home.models import Greeting
from about.models import About
from resume.models import Field
from services.models import Introduction, Service
from projects.models import Project, ProjectIntro
from contact.models import Contact
from contact.forms import ContactForm
from django.core.mail import send_mail
import os
from django.contrib import messages



def main(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        subject = form.cleaned_data['name']
        from_email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        send_mail(subject, message, from_email, [os.environ.get(str('EMAIL_USER'))])
        messages.success(request, 'Message sent')
        form = ContactForm()
        return redirect('/')




    # home
    home = Greeting.objects.first()
    skill1 = home.skills.first()
    skill2 = home.skills.all()[1]
    skill3 = home.skills.all()[2]
    skill4 = home.skills.all()[3]

    # about
    about = About.objects.first()

    # resume
    fields = Field.objects.all()

    # services
    introduction = Introduction.objects.first()
    services = Service.objects.all()

    # projects
    printro = ProjectIntro.objects.first()
    projects = Project.objects.all()

    # contact
    contact = Contact.objects.first()

    context = {
        # home
        'home': home,
        'skill1': skill1,
        'skill2': skill2,
        'skill3': skill3,
        'skill4': skill4,

        # about
        'about': about,

        # resume
        'fields': fields,

        # services
        'introduction': introduction,
        'services': services,

        # projects
        'printro': printro,
        'projects': projects,

        # contact
        'contact': contact,
        'form': form,
    }


    return render(request, 'main/main.html', context=context)

owner/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.shortcuts import render

# Create your views here.

resume/views.py
from django.shortcuts import render

# Create your views here.

services/views.py
from django.shortcuts import render

# Create your views here.

templates/about/about.html
{% load static %}
<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
    <div class="container">
        <div class="row d-flex no-gutters">
            <div class="col-md-6 col-lg-6 d-flex">
                <div class="img-about mt-5 img d-flex align-items-stretch">
                    <div class="overlay"></div>
                    <div class="img rounded-circle h-75 d-flex align-self-stretch align-items-center" style="background-image:url({{ about.user.images.url }});">
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
              <div class="col-md-12 heading-section ftco-animate">
                <h1 class="big">About</h1>
                <h2 class="mb-4">{{ about.starter }}</h2>
                <p>{{ about.description }}</p>
                <ul class="about-info mt-4 px-md-0 px-2">
                    <li class="d-flex"><span>Name:</span> <span>{{ about.user.full_name }}</span></li>
                    <li class="d-flex"><span>Date of birth:</span> <span>{{ about.user.date_of_birth }}</span></li>
                    <li class="d-flex"><span>Address:</span> <span>{{ about.user.address }}</span></li>
                    <li class="d-flex"><span>Email:</span> <span>{{ about.user.email }}</span></li>
                    <li class="d-flex"><span>Phone: </span> <span>{{ about.user.phone }}</span></li>
                </ul>
              </div>
            </div>
          <div class="counter-wrap ftco-animate d-flex mt-md-3">
          <div class="text">
            <p class="mb-4">
                <span class="number" data-number="{{ about.user.projects }}">0</span>
                <span>Project complete</span>
            </p>
            <p><a href="#" class="btn btn-primary py-3 px-3">Download CV</a></p>
          </div>
          </div>
        </div>
    </div>
    </div>
</section>

<section class="ftco-section ftco-partner">
    <div class="container">
        <div class="row">
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{% static 'images/partner-1.png' %}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{% static 'images/partner-2.png'%}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{% static 'images/download.png' %}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{% static 'images/partner-4.png' %}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-sm ftco-animate">
                <a href="#" class="partner"><img src="{% static 'images/Django_logo.png' %}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
        </div>
    </div>
</section>

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        {#  Google Font      #}
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
        {#   CSS Files     #}
        <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">


        <title>VulKan --Home</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
	        <div class="container">
	            <a class="navbar-brand" href="{%  url 'main' %}"><span>D</span>oniyor</a>
	            <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	                <span class="oi oi-menu"></span> Menu
	            </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav nav ml-auto">
                      <li class="nav-item"><a href="#home-section" class="nav-link"><span>Home</span></a></li>
                      <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>
                      <li class="nav-item"><a href="#resume-section" class="nav-link"><span>Resume</span></a></li>
                      <li class="nav-item"><a href="#services-section" class="nav-link"><span>Services</span></a></li>
                      <li class="nav-item"><a href="#projects-section" class="nav-link"><span>Projects</span></a></li>
                      <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>
                    </ul>
                </div>
	        </div>
	    </nav>

        {% block content %}

        {% endblock %}

        <footer class="ftco-footer ftco-section">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-md">
                        <div class="ftco-footer-widget mb-4">
                            <h2 class="ftco-heading-2">About</h2>
                            <p>Always ready for help and work in teams</p>
                            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                                <li class="ftco-animate"><a href="https://t.me/Umnik_818"><span class="icon-telegram"></span></a></li>
                                <li class="ftco-animate"><a href="https://twitter.com/DONIYOR79323852"><span class="icon-twitter"></span></a></li>
                                <li class="ftco-animate"><a href="https://www.instagram.com/gayratovic77/?hl=en"><span class="icon-instagram"></span></a></li>
                                <li class="ftco-animate"><a href="https://github.com/DoniDev"><span class="icon-github"></span></a></li>
                            </ul>
                        </div>
                    </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#home-section"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                            <li><a href="#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                            <li><a href="#resume-section"><span class="icon-long-arrow-right mr-2"></span>Resume</a></li>
                            <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                            <li><a href="#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                            <li><a href="#contact-section"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Services</h2>
                        <ul class="list-unstyled">
                            <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>OpenCV</a></li>
                            <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                            <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Python Development</a></li>
                            <li><a href="#services-section"><span class="icon-long-arrow-right mr-2"></span>Django</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">Tashkent Uzbekistan</span></li>
                                <li><a href="tel://+998 99 818 65 92"><span class="icon icon-phone"></span><span class="text">+ 998 99 818 65 92</span></a></li>
                                <li><a href="mailto:dabduvokhidov@gmail.com"><span class="icon icon-envelope"></span><span class="text">dabduvokhidov@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                <div class="row">
                    <div class="col-md-12 text-center">

                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made <i  aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Doniyor</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </footer>

        <script src=" {% static 'js/jquery.min.js' %}"></script>
        <script src=" {% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
        <script src=" {% static 'js/popper.min.js' %}"></script>
        <script src=" {% static 'js/bootstrap.min.js' %}"></script>
        <script src=" {% static 'js/jquery.easing.1.3.js' %}"></script>
        <script src=" {% static 'js/jquery.waypoints.min.js' %}"></script>
        <script src=" {% static 'js/jquery.stellar.min.js' %}"></script>
        <script src=" {% static 'js/owl.carousel.min.js' %}"></script>
        <script src=" {% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src=" {% static 'js/aos.js' %}"></script>
        <script src=" {% static 'js/jquery.animateNumber.min.js' %}"></script>
        <script src=" {% static 'js/scrollax.min.js' %}"></script>
        <script src=" {% static 'js/main.js' %}"></script>

    </body>
</html>

templates/contact/contact.html
{% load static %}
{% load crispy_forms_tags %}
{#<section class="ftco-section ftco-hireme img" style="background-image: url({% static 'images/bg_1.jpg' %})">#}
{#    <div class="overlay"></div>#}
{#    <div class="container">#}
{#        <div class="row justify-content-center">#}
{#            <div class="col-md-7 ftco-animate text-center">#}
{#                <h2>I'm <span>Available</span> for freelancing</h2>#}
{#                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>#}
{#                <p class="mb-0"><a href="#" class="btn btn-primary py-3 px-5">Hire me</a></p>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}

<section class="ftco-section contact-section ftco-no-pb mb-5" id="contact-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section text-center ftco-animate">
                <h1 class="big big-2">Contact</h1>
                <h2 class="mb-4">{{ contact.title }}</h2>
                <p>{{ contact.description }}</p>
            </div>
        </div>

        <div class="row d-flex contact-info mb-5">
            <div class="col-md-6 col-lg-4 d-flex ftco-animate">
                <div class="align-self-stretch box text-center p-4 shadow">
                    <div class="icon d-flex align-items-center justify-content-center">
          			    <span class="icon-map-signs"></span>
          		    </div>
          		    <div>
                        <h3 class="mb-4">Address</h3>
		                <p>{{ contact.credentials.address }}</p>
		            </div>
	            </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex ftco-animate">
          	    <div class="align-self-stretch box text-center p-4 shadow">
          		    <div class="icon d-flex align-items-center justify-content-center">
          			    <span class="icon-phone2"></span>
          		    </div>
          		    <div>
	          		    <h3 class="mb-4">Contact Number</h3>
		                <p><a href="tel://{{ contact.credentials.phone }}">{{ contact.credentials.phone }}</a></p>
	                </div>
	            </div>
            </div>
            <div class="col-md-6 col-lg-4 d-flex ftco-animate">
          	    <div class="align-self-stretch box text-center p-4 shadow">
          		    <div class="icon d-flex align-items-center justify-content-center">
          			    <span class="icon-paper-plane"></span>
          		    </div>
          		    <div>
	          		    <h3 class="mb-4">Email Address</h3>
		                <p><a href="mailto:{{ contact.credentials.email }}">{{ contact.credentials.email }}</a></p>
		            </div>
	            </div>
            </div>
        </div>


        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}
        <div class="row no-gutters block-9">
            <div class="col-md-6 order-md-last d-flex">
                <form action="#" class="bg-light p-4 p-md-5 contact-form" method="POST">
                    {% csrf_token %}

                    {{ form|crispy }}
                    <button class="btn btn-primary btn-block" type="submit">Send</button>
                </form>
            </div>

            <div class="col-md-6 d-flex">
          	    <div class="img" style="background-image: url({{ contact.image.url }});"></div>
            </div>
        </div>
    </div>
</section>

templates/home/home.html
<section class="hero-wrap js-fullheight">
  <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
            <div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-center">
                <div class="text text-center">
                    <span class="subheading">{{ home.starting }}</span>
                    <h1>{{ home.name.full_name }}</h1>
                        <h2>{{ home.intro }}
                            <span
                             class="txt-rotate"
                             data-period="2000"
                             data-rotate='["{{ skill1 }}","{{ skill2 }}","{{ skill3 }}", "{{ skill4 }}"]'></span>
                        </h2>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div class="mouse">
            <a href="#" class="mouse-icon">
                <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
            </a>
        </div>
</section>

templates/main/main.html
{% extends 'base.html' %}

{% block content %}
    {% include 'home/home.html' %}
    {% include 'about/about.html' %}
    {% include 'resume/resume.html' %}
    {% include 'services/service.html' %}
    {% include 'projects/projects.html' %}
    {% include 'contact/contact.html' %}


{% endblock %}

templates/projects/projects.html
{% load static %}
<section class="ftco-section ftco-project" id="projects-section">
    <div class="container-fluid px-md-0">
        <div class="row no-gutters justify-content-center pb-5">
            <div class="col-md-12 heading-section text-center ftco-animate">
                <h1 class="big big-2">Projects</h1>
                <h2 class="mb-4">{{ printro.title }}</h2>
                <p>{{ printro.description }}</p>
            </div>
        </div>
        <div class="row no-gutters">
            {% for project in projects %}
            <div class="col-md-4">
                <div class="project img ftco-animate d-flex justify-content-center align-items-center" style="background-image: url({{ project.image.url }});">
                    <div class="overlay"></div>
                    <div class="text text-center p-4">
                        <h3><a href="#">{{ project.name }}</a></h3>
                        <span>{{ project.technology }}</span><br>
                        <a class="text-white"  href="{{ project.link }}">Github</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/resume/resume.html
<section class="ftco-section ftco-no-pb goto-here" id="resume-section">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <nav id="navi">
                    <ul>
                      {% for field in fields %}
                          <li><a href="#page-{{ forloop.counter}}">{{ field.name }}</a></li>
                      {% endfor %}
                    </ul>
                </nav>
            </div>

            <div class="col-md-9">
                {% for field in fields %}
                <div id="page-{{ forloop.counter }}" class= "page-{{ forloop.counter }}">
                    <h2 class="heading">{{ field.name }}</h2>
                    {% for activity in field.activity_set.all %}
                    <div class="resume-wrap d-flex ftco-animate">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="flaticon-ideas"></span>
                        </div>
                        <div class="text pl-3">
                            <span class="date">{{ activity.duration }}</span>
                            <h2>{{ activity.job }}</h2>
                            <span class="position">{{ activity.location }}</span>
                            <p>{{ activity.description }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

templates/services/service.html
<section class="ftco-section" id="services-section">
    <div class="container-fluid px-md-5">
        <div class="row justify-content-center py-5 mt-5">
            <div class="col-md-12 heading-section text-center ftco-animate">
                <h1 class="big big-2">Services</h1>
                <h2 class="mb-4">{{ introduction.title }}</h2>
                <p>{{ introduction.description }}</p>
            </div>
        </div>
        <div class="row">
            {% for service in services %}
            <div class="col-md-4 text-center d-flex ftco-animate">
                <a href="#" class="services-1 shadow">
                    <span class="icon">
                        <i class="flaticon-{{ service.icon}}"></i>
                    </span>
                    <div class="desc">
                        <h3 class="mb-5">{{ service.name }}</h3>
                        <p>{{ service.heading }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>